# Generated by Django 6.1 on 2026-09-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo_actividad', models.CharField(max_length=100)),
                ('servicio', models.CharField(max_length=100)),
                ('tipo_atencion', models.CharField(blank=True, max_length=100, null=True)),
                ('subtipo_atencion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('dias_computables', models.IntegerField()),
                ('estado', models.CharField(default='Abierto', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemMedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nombre_item', models.CharField(max_length=150)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.cargo')),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configuration.catalogoactividad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('valor_objetivo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ponderacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('umbral_minimo', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('maximo_computable', models.DecimalField(decimal_places=2, default=150.0, max_digits=5)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.funcionario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configuration.itemmedicion')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configuration.periodo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
