# Generated by Django 6.1 on 2026-09-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracionmeta',
            unique_together={('item', 'periodo', 'funcionario')},
        ),
    ]
