# Generated by Django 6.1.1 on 2026-09-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_configuracionmeta_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogoactividad',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20),
        ),
    ]
