# Generated by Django 6.1 on 2026-09-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('codigo_evidencia_unico', models.CharField(max_length=50, unique=True)),
                ('fecha_actividad', models.DateField()),
                ('descripcion_solicitud', models.TextField()),
                ('accion_ejecutada', models.TextField()),
                ('contacto_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.funcionario')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configuration.itemmedicion')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configuration.periodo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtencionSocialGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('numero_gestion', models.IntegerField()),
                ('tipo_gestion', models.CharField(max_length=100)),
                ('fecha_gestion', models.DateField()),
                ('resultado_gestion', models.TextField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.actividad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ruta_archivo_url', models.CharField(max_length=255)),
                ('metadatos', models.TextField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='activities.actividad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ValidacionEvidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.CharField(max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.actividad')),
                ('verificador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
