# Generated by Django 6.1 on 2026-09-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='atencionsocialgestion',
            unique_together={('actividad', 'numero_gestion')},
        ),
    ]
