# Generated by Django 6.1 on 2026-09-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_atencionsocialgestion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='codigo_evidencia_unico',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
