# Generated by Django 6.1 on 2026-09-18 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('activities', '0001_initial'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteDesempenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('concepto', models.CharField(max_length=50)),
                ('valor_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('motivo', models.TextField()),
                ('autorizador', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ajustes_autorizados', to='accounts.funcionario')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ajustes', to='accounts.funcionario')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='configuration.periodo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompromisoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('solicitante', models.CharField(max_length=100)),
                ('territorio', models.CharField(blank=True, max_length=100, null=True)),
                ('area_apoyo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_comprometida', models.DateField()),
                ('estado', models.CharField(default='Ingresado', max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('actividad_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.actividad')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='accounts.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
