# Generated by Django 6.1.1 on 2026-09-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compromisoagenda',
            name='estado',
            field=models.CharField(choices=[('Ingresado', 'Ingresado'), ('Pendiente', 'Pendiente'), ('En proceso', 'En proceso'), ('Realizado', 'Realizado')], default='Ingresado', max_length=30),
        ),
    ]
